[package]
name = "crypto_provider_openssl"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
crypto_provider = { path = "../crypto_provider", default-features = false, features = ["alloc", "std"] }
openssl.workspace = true
cfg-if.workspace = true

ouroboros = "0.15.5"

[features]
default = []
boringssl = ["openssl/unstable_boringssl", "crypto_provider/gcm_siv"]

[dev-dependencies]
crypto_provider_test.workspace = true
rstest.workspace = true
hex-literal.workspace = true
