# The packages to override
paths = [
    "../boringssl-build/boringssl/build/rust/bssl-sys",
    "../boringssl-build/rust-openssl/openssl",
    "../boringssl-build/rust-openssl/openssl-sys",
]

[env]
WORKSPACE_DIR = { value = "", relative = true }



