[env]
WORKSPACE_DIR = { value = "", relative = true }

[patch.crates-io]
bssl-sys = { path = "../boringssl-build/boringssl/build/rust" }
openssl = { path = "../boringssl-build/rust-openssl/openssl" }
openssl-sys = { path = "../boringssl-build/rust-openssl/openssl-sys" }
